### ISSUE TITLE
Armory and signatures for signing config changes

### ISSUE THREAD

**Issue by pee** [wizkid057/wizstats#36]
I can't seem to get Armory to generate a correct signature to change opions in eligius.  When  I generate the message and check verify in armory it shows as OK.

**Comment by wizkid057** [comment]
Armory does not use standard signatures.  They invented their own signature setup which I haven't had time to dissect and implement a standalone verification for.

**Comment by pee** [comment]
What would you suggest using as an alternative. (Besides Mt. Gox).

-pee

**Comment by wizkid057** [comment]
standard bitcoin-qt / bitcoind generate correct signatures.

**Comment by pee** [comment]
Can you recommend and example while i search through google/github on on
how to do this. I seem to be doing something incorrectly.

You're time is greatly appreciated.

-pee

**Comment by DNAUplink** [comment]
If you want to use the Armory, you can export your private key from Armory, then import it into Bitcoin-Qt, then you can sign with that wallet address.  Otherwise just use a new address from bitcoinqt for your worker id, this is easier.  

In BitcoinQt >>>File>>>Sign Message>>>select correct workerWalletAddress>>>Enter Messsage from Eligius>>>Sign Message.

I hope it helps.

**Comment by wizkid057** [comment]
The latest version of armory supposedly supports bitcoin-qt/standard signatures.
